### ISSUE TITLE
glibc check too intrusive

### ISSUE THREAD

**Issue by leahneukirchen** [niklata/ndhc#1]
The check for glibc should not fail, but assume that -lrt is not required.  This will simplify cross-building (where try_run doesn't work) and support alternative libc such as musl.

**Comment by niklata** [comment]
Thanks for the report!  Should be fixed now.

**Comment by leahneukirchen** [comment]
It works with musl now, but cross-compiling still fails:

```
CMake Error: TRY_RUN() invoked in cross-compiling mode, please set the following cache variables appropriately:
   GLIBC_DETECTION (advanced)
   GLIBC_DETECTION__TRYRUN_OUTPUT (advanced)
For details see /builddir/ndhc-20150212/build/TryRunResults.cmake
Could not detect glibc version.
```

Perhaps the whole try_run should be guarded with `if(CMAKE_CROSSCOMPILE)`.

**Comment by niklata** [comment]
I've disabled the glibc version detection when CMAKE_CROSSCOMPILE is set.  Please let me know if there's still trouble when cross-compiling.

**Comment by leahneukirchen** [comment]
My bad, the flag is actually called CMAKE_CROSSCOMPILING. When I replace this, it works fine.
